/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/apis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List apis */
        get: operations["listAPIs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apis/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        /** Get a API */
        get: operations["getAPI"];
        /** Create or update a API */
        put: operations["putAPI"];
        post?: never;
        /** Delete a API */
        delete: operations["deleteAPI"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk apply resources
         * @description Creates or updates multiple resources in a single request.
         */
        post: operations["applyResources"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deployments */
        get: operations["listDeployments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        /** Get a Deployment */
        get: operations["getDeployment"];
        /** Create or update a Deployment */
        put: operations["putDeployment"];
        post?: never;
        /** Delete a Deployment */
        delete: operations["deleteDeployment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List environments */
        get: operations["listEnvironments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        /** Get a Environment */
        get: operations["getEnvironment"];
        /** Create or update a Environment */
        put: operations["putEnvironment"];
        post?: never;
        /** Delete a Environment */
        delete: operations["deleteEnvironment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gatewayprofiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gatewayprofiles */
        get: operations["listGatewayProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gatewayprofiles/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        /** Get a GatewayProfile */
        get: operations["getGatewayProfile"];
        /** Create or update a GatewayProfile */
        put: operations["putGatewayProfile"];
        post?: never;
        /** Delete a GatewayProfile */
        delete: operations["deleteGatewayProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gateways */
        get: operations["listGateways"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        /** Get a Gateway */
        get: operations["getGateway"];
        /** Create or update a Gateway */
        put: operations["putGateway"];
        post?: never;
        /** Delete a Gateway */
        delete: operations["deleteGateway"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/{name}/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gateway name */
                name: string;
            };
            cookie?: never;
        };
        /**
         * Generate Envoy bootstrap configuration
         * @description Generates an Envoy bootstrap YAML for the gateway, using the referenced profile's settings (admin port, xDS cluster, etc.).
         */
        get: operations["getGatewayBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateways/{name}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gateway name */
                name: string;
            };
            cookie?: never;
        };
        /**
         * Get gateway deployment instructions
         * @description Returns Docker run command, Docker Compose snippet, and Kubernetes manifest for deploying the gateway's Envoy proxy.
         */
        get: operations["getGatewayDeployInstructions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listeners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List listeners */
        get: operations["listListeners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listeners/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        /** Get a Listener */
        get: operations["getListener"];
        /** Create or update a Listener */
        put: operations["putListener"];
        post?: never;
        /** Delete a Listener */
        delete: operations["deleteListener"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload API bundle
         * @description Uploads a ZIP bundle containing an API spec and flowc.yaml. Creates an API resource and optionally a Deployment resource.
         */
        post: operations["uploadBundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIListResponse: {
            items: components["schemas"]["APIResponse"][];
            kind: string;
            total: number;
        };
        APIPutRequest: {
            metadata?: {
                conflictPolicy?: components["schemas"]["ConflictPolicy"];
                labels?: {
                    [key: string]: string;
                };
            };
            spec: components["schemas"]["APISpec"];
        };
        APIResponse: {
            kind: components["schemas"]["ResourceKind"];
            metadata: components["schemas"]["ResourceMeta"];
            spec: components["schemas"]["APISpec"];
            status?: components["schemas"]["APIStatus"];
        };
        APISpec: {
            apiType?: string;
            context: string;
            description?: string;
            displayName?: string;
            policyChain?: components["schemas"]["PolicyInstance"][];
            routing?: components["schemas"]["RoutingConfig"];
            specContent?: string;
            upstream: components["schemas"]["UpstreamConfig"];
            version: string;
        };
        APIStatus: {
            conditions?: components["schemas"]["Condition"][];
            parsedInfo?: components["schemas"]["ParsedInfo"];
            phase: string;
        };
        AccessLogsConfig: {
            enabled: boolean;
            format?: string;
            path?: string;
        };
        ApplyRequest: {
            resources: {
                [key: string]: unknown;
            }[];
        };
        ApplyResult: {
            results: components["schemas"]["ApplyResultItem"][];
        };
        ApplyResultItem: {
            action: string;
            error?: string;
            kind: components["schemas"]["ResourceKind"];
            name: string;
        };
        BlueGreenConfig: {
            ActiveVersion: string;
            AutoPromote: boolean;
            StandbyVersion: string;
        };
        BootstrapConfig: {
            /** Format: int32 */
            adminPort?: number;
            staticResources?: {
                [key: string]: unknown;
            };
            xdsClusterName?: string;
        };
        CanaryConfig: {
            BaselineVersion: string;
            CanaryVersion: string;
            /** Format: int64 */
            CanaryWeight: number;
            MatchCriteria?: components["schemas"]["MatchCriteria"];
        };
        Condition: {
            /** Format: date-time */
            lastTransitionTime: string;
            message?: string;
            reason?: string;
            status: string;
            type: string;
        };
        /** @enum {string} */
        ConflictPolicy: "strict" | "warn" | "takeover";
        DeleteResponse: {
            message: string;
        };
        DeployInstructions: {
            docker: components["schemas"]["DockerInstructions"];
            gateway: components["schemas"]["GatewayInfo"];
            kubernetes: components["schemas"]["K8sInstructions"];
        };
        DeploymentListResponse: {
            items: components["schemas"]["DeploymentResponse"][];
            kind: string;
            total: number;
        };
        DeploymentPutRequest: {
            metadata?: {
                conflictPolicy?: components["schemas"]["ConflictPolicy"];
                labels?: {
                    [key: string]: string;
                };
            };
            spec: components["schemas"]["DeploymentSpec"];
        };
        DeploymentResponse: {
            kind: components["schemas"]["ResourceKind"];
            metadata: components["schemas"]["ResourceMeta"];
            spec: components["schemas"]["DeploymentSpec"];
            status?: components["schemas"]["DeploymentStatus"];
        };
        DeploymentSpec: {
            apiRef: string;
            environmentRef: string;
            gatewayRef: string;
            listenerRef: string;
            strategy?: components["schemas"]["StrategyConfig"];
        };
        DeploymentStatus: {
            conditions?: components["schemas"]["Condition"][];
            phase: string;
            xdsSnapshotVersion?: string;
        };
        DeploymentStrategyConfig: {
            blue_green?: components["schemas"]["BlueGreenConfig"];
            canary?: components["schemas"]["CanaryConfig"];
            type: string;
        };
        DockerInstructions: {
            bootstrapUrl: string;
            composeSnippet: string;
            runCommand: string;
        };
        EnvironmentListResponse: {
            items: components["schemas"]["EnvironmentResponse"][];
            kind: string;
            total: number;
        };
        EnvironmentPutRequest: {
            metadata?: {
                conflictPolicy?: components["schemas"]["ConflictPolicy"];
                labels?: {
                    [key: string]: string;
                };
            };
            spec: components["schemas"]["EnvironmentSpec"];
        };
        EnvironmentResponse: {
            kind: components["schemas"]["ResourceKind"];
            metadata: components["schemas"]["ResourceMeta"];
            spec: components["schemas"]["EnvironmentSpec"];
            status?: components["schemas"]["EnvironmentStatus"];
        };
        EnvironmentSpec: {
            gatewayRef: string;
            hostname: string;
            httpFilters?: components["schemas"]["HTTPFilter"][];
            listenerRef: string;
        };
        EnvironmentStatus: {
            conditions?: components["schemas"]["Condition"][];
            phase: string;
        };
        ErrorResponse: {
            /** Format: int64 */
            code: number;
            details?: {
                [key: string]: string;
            };
            error: string;
        };
        GatewayInfo: {
            envoyImage: string;
            name: string;
            nodeId: string;
            profile?: string;
        };
        GatewayListResponse: {
            items: components["schemas"]["GatewayResponse"][];
            kind: string;
            total: number;
        };
        GatewayProfileListResponse: {
            items: components["schemas"]["GatewayProfileResponse"][];
            kind: string;
            total: number;
        };
        GatewayProfilePutRequest: {
            metadata?: {
                conflictPolicy?: components["schemas"]["ConflictPolicy"];
                labels?: {
                    [key: string]: string;
                };
            };
            spec: components["schemas"]["GatewayProfileSpec"];
        };
        GatewayProfileResponse: {
            kind: components["schemas"]["ResourceKind"];
            metadata: components["schemas"]["ResourceMeta"];
            spec: components["schemas"]["GatewayProfileSpec"];
            status?: components["schemas"]["GatewayProfileStatus"];
        };
        GatewayProfileSpec: {
            allowedPolicies?: string[];
            bootstrap?: components["schemas"]["BootstrapConfig"];
            defaultHttpFilters?: components["schemas"]["HTTPFilter"][];
            defaultStrategy?: components["schemas"]["StrategyConfig"];
            description?: string;
            displayName: string;
            envoyImage?: string;
            listenerPresets?: components["schemas"]["ListenerPreset"][];
            profileType: string;
        };
        GatewayProfileStatus: {
            conditions?: components["schemas"]["Condition"][];
            /** Format: int64 */
            gatewayCount?: number;
            phase: string;
        };
        GatewayPutRequest: {
            metadata?: {
                conflictPolicy?: components["schemas"]["ConflictPolicy"];
                labels?: {
                    [key: string]: string;
                };
            };
            spec: components["schemas"]["GatewaySpec"];
        };
        GatewayResponse: {
            kind: components["schemas"]["ResourceKind"];
            metadata: components["schemas"]["ResourceMeta"];
            spec: components["schemas"]["GatewaySpec"];
            status?: components["schemas"]["GatewayStatus"];
        };
        GatewaySpec: {
            defaults?: components["schemas"]["StrategyConfig"];
            nodeId: string;
            profileRef?: string;
        };
        GatewayStatus: {
            conditions?: components["schemas"]["Condition"][];
            phase: string;
        };
        HTTPFilter: {
            config: {
                [key: string]: unknown;
            };
            name: string;
        };
        HealthCheckConfig: {
            enabled: boolean;
            /** Format: int32 */
            expected_status?: number;
            /** Format: int32 */
            healthy_count?: number;
            interval?: string;
            path?: string;
            timeout?: string;
            /** Format: int32 */
            unhealthy_count?: number;
        };
        HealthResponse: {
            status: string;
            /** Format: date-time */
            timestamp: string;
            uptime: string;
            version: string;
        };
        K8sInstructions: {
            applyCommand: string;
            manifest: string;
        };
        ListenerListResponse: {
            items: components["schemas"]["ListenerResponse"][];
            kind: string;
            total: number;
        };
        ListenerPreset: {
            address?: string;
            http2?: boolean;
            name: string;
            /** Format: int32 */
            port: number;
            tls?: components["schemas"]["TLSConfig"];
        };
        ListenerPutRequest: {
            metadata?: {
                conflictPolicy?: components["schemas"]["ConflictPolicy"];
                labels?: {
                    [key: string]: string;
                };
            };
            spec: components["schemas"]["ListenerSpec"];
        };
        ListenerResponse: {
            kind: components["schemas"]["ResourceKind"];
            metadata: components["schemas"]["ResourceMeta"];
            spec: components["schemas"]["ListenerSpec"];
            status?: components["schemas"]["ListenerStatus"];
        };
        ListenerSpec: {
            address?: string;
            gatewayRef: string;
            http2?: boolean;
            /** Format: int32 */
            port: number;
            tls?: components["schemas"]["TLSConfig"];
        };
        ListenerStatus: {
            conditions?: components["schemas"]["Condition"][];
            phase: string;
        };
        LoadBalancingStrategyConfig: {
            /** Format: int32 */
            choice_count?: number;
            cookie_name?: string;
            hash_on?: string;
            header_name?: string;
            health_check?: components["schemas"]["HealthCheckConfig"];
            type: string;
        };
        MatchCriteria: {
            Headers: {
                [key: string]: string;
            };
            QueryParams: {
                [key: string]: string;
            };
            SourceLabels: {
                [key: string]: string;
            };
        };
        MetricsConfig: {
            enabled: boolean;
            path?: string;
            /** Format: int32 */
            port?: number;
            provider?: string;
        };
        ObservabilityStrategyConfig: {
            access_logs?: components["schemas"]["AccessLogsConfig"];
            metrics?: components["schemas"]["MetricsConfig"];
            tracing?: components["schemas"]["TracingConfig"];
        };
        ParsedInfo: {
            paths?: string[];
            servers?: string[];
            title?: string;
            version?: string;
        };
        PolicyInstance: {
            config?: {
                [key: string]: unknown;
            };
            enabled: boolean;
            id: string;
            inheritanceMode?: string;
            /** Format: int64 */
            order: number;
            policyType: string;
        };
        RateLimitStrategyConfig: {
            /** Format: int32 */
            burst_size?: number;
            claim_name?: string;
            cookie_name?: string;
            external_service?: string;
            header_name?: string;
            identify_by?: string;
            /** Format: int32 */
            requests_per_minute?: number;
            type: string;
        };
        /** @enum {string} */
        ResourceKind: "Gateway" | "GatewayProfile" | "Listener" | "Environment" | "API" | "Deployment";
        ResourceMeta: {
            conflictPolicy?: components["schemas"]["ConflictPolicy"];
            /** Format: date-time */
            createdAt: string;
            kind: components["schemas"]["ResourceKind"];
            labels?: {
                [key: string]: string;
            };
            managedBy?: string;
            name: string;
            /** Format: int64 */
            revision: number;
            /** Format: date-time */
            updatedAt: string;
        };
        RetryStrategyConfig: {
            /** Format: double */
            budget_percent?: number;
            /** Format: int32 */
            max_retries?: number;
            per_try_timeout?: string;
            retriable_status_codes?: number[];
            retry_on?: string;
            type: string;
        };
        RouteMatchStrategyConfig: {
            case_sensitive?: boolean;
            type: string;
            version_header?: string;
        };
        RoutingConfig: {
            caseSensitive?: boolean;
            loadBalancing?: string;
            matchType?: string;
        };
        StrategyConfig: {
            deployment?: components["schemas"]["DeploymentStrategyConfig"];
            load_balancing?: components["schemas"]["LoadBalancingStrategyConfig"];
            observability?: components["schemas"]["ObservabilityStrategyConfig"];
            rate_limiting?: components["schemas"]["RateLimitStrategyConfig"];
            retry?: components["schemas"]["RetryStrategyConfig"];
            route_matching?: components["schemas"]["RouteMatchStrategyConfig"];
        };
        TLSConfig: {
            caPath?: string;
            certPath: string;
            cipherSuites?: string[];
            keyPath: string;
            minVersion?: string;
            requireClientCert?: boolean;
        };
        TracingConfig: {
            enabled: boolean;
            endpoint?: string;
            provider?: string;
            /** Format: double */
            sampling_rate?: number;
        };
        UpstreamConfig: {
            host: string;
            /** Format: int32 */
            port: number;
            scheme?: string;
            timeout?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAPIs: {
        parameters: {
            query?: {
                /** @description Label filter (comma-separated key=value pairs) */
                labels?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of apis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIListResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAPI: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putAPI: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
                /** @description Identifier of the managing entity for ownership tracking */
                "X-Managed-By"?: string;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["APIPutRequest"];
            };
        };
        responses: {
            /** @description Resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteAPI: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    applyResources: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identifier of the managing entity for ownership tracking */
                "X-Managed-By"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description Apply results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResult"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listDeployments: {
        parameters: {
            query?: {
                /** @description Label filter (comma-separated key=value pairs) */
                labels?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of deployments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentListResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Deployment resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putDeployment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
                /** @description Identifier of the managing entity for ownership tracking */
                "X-Managed-By"?: string;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeploymentPutRequest"];
            };
        };
        responses: {
            /** @description Resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentResponse"];
                };
            };
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteDeployment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listEnvironments: {
        parameters: {
            query?: {
                /** @description Label filter (comma-separated key=value pairs) */
                labels?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of environments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentListResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Environment resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putEnvironment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
                /** @description Identifier of the managing entity for ownership tracking */
                "X-Managed-By"?: string;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentPutRequest"];
            };
        };
        responses: {
            /** @description Resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteEnvironment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listGatewayProfiles: {
        parameters: {
            query?: {
                /** @description Label filter (comma-separated key=value pairs) */
                labels?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of gatewayprofiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayProfileListResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGatewayProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The GatewayProfile resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayProfileResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putGatewayProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
                /** @description Identifier of the managing entity for ownership tracking */
                "X-Managed-By"?: string;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayProfilePutRequest"];
            };
        };
        responses: {
            /** @description Resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayProfileResponse"];
                };
            };
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayProfileResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteGatewayProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listGateways: {
        parameters: {
            query?: {
                /** @description Label filter (comma-separated key=value pairs) */
                labels?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of gateways */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayListResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGateway: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Gateway resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putGateway: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
                /** @description Identifier of the managing entity for ownership tracking */
                "X-Managed-By"?: string;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayPutRequest"];
            };
        };
        responses: {
            /** @description Resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayResponse"];
                };
            };
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteGateway: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGatewayBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gateway name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Envoy bootstrap YAML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-yaml": string;
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGatewayDeployInstructions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Gateway name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment instructions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployInstructions"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listListeners: {
        parameters: {
            query?: {
                /** @description Label filter (comma-separated key=value pairs) */
                labels?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of listeners */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenerListResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getListener: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Listener resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenerResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putListener: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
                /** @description Identifier of the managing entity for ownership tracking */
                "X-Managed-By"?: string;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListenerPutRequest"];
            };
        };
        responses: {
            /** @description Resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenerResponse"];
                };
            };
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenerResponse"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteListener: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resource revision for optimistic concurrency control */
                "If-Match"?: number;
            };
            path: {
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Error response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploadBundle: {
        parameters: {
            query?: never;
            header?: {
                /** @description Identifier of the managing entity for ownership tracking */
                "X-Managed-By"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Upload results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResult"];
                };
            };
            /** @description Error response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
